services:
  db:
    image: postgres
    container_name: fightcore_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: localcontainer
    volumes:
      - ./db-data:/var/lib/postgresql/data 

volumes:
  db-data:
    driver: local