services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: fightcore_sql_server
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - './bak:/home/bak'
