// <auto-generated />
using FightCore.FrameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FightCore.Data.Migrations
{
    [DbContext(typeof(FrameDataContext))]
    [Migration("20260430184042_Added_AnimationCredits")]
    partial class Added_AnimationCredits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FightCore.Models.AlternativeAnimation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreditId")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text")
                        .HasColumnName("gif_url");

                    b.Property<long>("MoveId")
                        .HasColumnType("bigint")
                        .HasColumnName("move_id");

                    b.Property<string>("PngUrl")
                        .HasColumnType("text")
                        .HasColumnName("png_url");

                    b.Property<string>("WebmUrl")
                        .HasColumnType("text")
                        .HasColumnName("webm_url");

                    b.HasKey("Id")
                        .HasName("pk_alternative_animations");

                    b.HasIndex("CreditId")
                        .HasDatabaseName("ix_alternative_animations_credit_id");

                    b.HasIndex("MoveId")
                        .HasDatabaseName("ix_alternative_animations_move_id");

                    b.ToTable("alternative_animations", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.AnimationCredit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_animation_credits");

                    b.ToTable("animation_credits", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CharacterInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_info_id");

                    b.Property<long?>("CharacterStatisticsId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_statistics_id");

                    b.Property<long>("FightCoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("fight_core_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("CharacterInfoId")
                        .HasDatabaseName("ix_characters_character_info_id");

                    b.HasIndex("CharacterStatisticsId")
                        .HasDatabaseName("ix_characters_character_statistics_id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.CharacterMiscInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discord")
                        .HasColumnType("text")
                        .HasColumnName("discord");

                    b.Property<string>("MeleeFrameData")
                        .HasColumnType("text")
                        .HasColumnName("melee_frame_data");

                    b.Property<string>("SsbWiki")
                        .HasColumnType("text")
                        .HasColumnName("ssb_wiki");

                    b.HasKey("Id")
                        .HasName("pk_characters_misc_infos");

                    b.ToTable("characters_misc_infos", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.CharacterStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanWallJump")
                        .HasColumnType("boolean")
                        .HasColumnName("can_wall_jump");

                    b.Property<int>("DashFrames")
                        .HasColumnType("integer")
                        .HasColumnName("dash_frames");

                    b.Property<double>("Gravity")
                        .HasColumnType("double precision")
                        .HasColumnName("gravity");

                    b.Property<double>("InitialDash")
                        .HasColumnType("double precision")
                        .HasColumnName("initial_dash");

                    b.Property<int>("JumpSquat")
                        .HasColumnType("integer")
                        .HasColumnName("jump_squat");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PLAIntangibilityFrames")
                        .HasColumnType("integer")
                        .HasColumnName("pla_intangibility_frames");

                    b.Property<double>("RunSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("run_speed");

                    b.Property<double>("WalkSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("walk_speed");

                    b.Property<double>("WaveDashLength")
                        .HasColumnType("double precision")
                        .HasColumnName("wave_dash_length");

                    b.Property<int>("WaveDashLengthRank")
                        .HasColumnType("integer")
                        .HasColumnName("wave_dash_length_rank");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_character_statistics");

                    b.ToTable("character_statistics", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Hit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("End")
                        .HasColumnType("integer")
                        .HasColumnName("end");

                    b.Property<long>("MoveId")
                        .HasColumnType("bigint")
                        .HasColumnName("move_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Start")
                        .HasColumnType("integer")
                        .HasColumnName("start");

                    b.HasKey("Id")
                        .HasName("pk_hits");

                    b.HasIndex("MoveId")
                        .HasDatabaseName("ix_hits_move_id");

                    b.ToTable("hits", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Hitbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Angle")
                        .HasColumnType("bigint")
                        .HasColumnName("angle");

                    b.Property<long>("BaseKnockback")
                        .HasColumnType("bigint")
                        .HasColumnName("base_knockback");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint")
                        .HasColumnName("damage");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<long>("HitId")
                        .HasColumnType("bigint")
                        .HasColumnName("hit_id");

                    b.Property<int>("HitlagAttacker")
                        .HasColumnType("integer")
                        .HasColumnName("hitlag_attacker");

                    b.Property<int>("HitlagAttackerCrouched")
                        .HasColumnType("integer")
                        .HasColumnName("hitlag_attacker_crouched");

                    b.Property<int>("HitlagDefender")
                        .HasColumnType("integer")
                        .HasColumnName("hitlag_defender");

                    b.Property<int>("HitlagDefenderCrouched")
                        .HasColumnType("integer")
                        .HasColumnName("hitlag_defender_crouched");

                    b.Property<bool>("IsWeightIndependent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_weight_independent");

                    b.Property<long>("KnockbackGrowth")
                        .HasColumnType("bigint")
                        .HasColumnName("knockback_growth");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SetKnockback")
                        .HasColumnType("bigint")
                        .HasColumnName("set_knockback");

                    b.Property<int>("Shieldstun")
                        .HasColumnType("integer")
                        .HasColumnName("shieldstun");

                    b.Property<int?>("YoshiArmorBreakPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("yoshi_armor_break_percentage");

                    b.HasKey("Id")
                        .HasName("pk_hitboxes");

                    b.HasIndex("HitId")
                        .HasDatabaseName("ix_hitboxes_hit_id");

                    b.ToTable("hitboxes", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Move", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnimationCreditId")
                        .HasColumnType("bigint")
                        .HasColumnName("animation_credit_id");

                    b.Property<int?>("AutoCancelAfter")
                        .HasColumnType("integer")
                        .HasColumnName("auto_cancel_after");

                    b.Property<int?>("AutoCancelBefore")
                        .HasColumnType("integer")
                        .HasColumnName("auto_cancel_before");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<int?>("End")
                        .HasColumnType("integer")
                        .HasColumnName("end");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text")
                        .HasColumnName("gif_url");

                    b.Property<int?>("IASA")
                        .HasColumnType("integer")
                        .HasColumnName("iasa");

                    b.Property<bool>("IsInterpolated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interpolated");

                    b.Property<int?>("LCanceledLandLag")
                        .HasColumnType("integer")
                        .HasColumnName("l_canceled_land_lag");

                    b.Property<int?>("LandLag")
                        .HasColumnType("integer")
                        .HasColumnName("land_lag");

                    b.Property<int?>("LandingFallSpecialLag")
                        .HasColumnType("integer")
                        .HasColumnName("landing_fall_special_lag");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<string>("PngUrl")
                        .HasColumnType("text")
                        .HasColumnName("png_url");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int?>("Start")
                        .HasColumnType("integer")
                        .HasColumnName("start");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("integer")
                        .HasColumnName("total_frames");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("WebmUrl")
                        .HasColumnType("text")
                        .HasColumnName("webm_url");

                    b.HasKey("Id")
                        .HasName("pk_moves");

                    b.HasIndex("AnimationCreditId")
                        .HasDatabaseName("ix_moves_animation_credit_id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_moves_character_id");

                    b.ToTable("moves", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.ScriptCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("HexString")
                        .HasColumnType("text")
                        .HasColumnName("hex_string");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<long?>("SubactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subaction_id");

                    b.Property<long>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SubactionId")
                        .HasDatabaseName("ix_script_commands_subaction_id");

                    b.ToTable("script_commands", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FightCore.Models.Subactions.MoveSubaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Frame")
                        .HasColumnType("integer")
                        .HasColumnName("frame");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer")
                        .HasColumnName("match_type");

                    b.Property<long>("MoveId")
                        .HasColumnType("bigint")
                        .HasColumnName("move_id");

                    b.Property<long>("SubactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subaction_id");

                    b.HasKey("Id")
                        .HasName("pk_move_subactions");

                    b.HasIndex("MoveId")
                        .HasDatabaseName("ix_move_subactions_move_id");

                    b.HasIndex("SubactionId")
                        .HasDatabaseName("ix_move_subactions_subaction_id");

                    b.ToTable("move_subactions", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Subaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subactions");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_subactions_character_id");

                    b.ToTable("subactions", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.SubactionHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ScriptOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("script_offset");

                    b.Property<long>("StringOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("string_offset");

                    b.Property<long>("SubactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subaction_id");

                    b.Property<long>("Unknown1Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("unknown1offset");

                    b.Property<long>("Unknown2Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("unknown2offset");

                    b.Property<long>("Unknown3Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("unknown3flags");

                    b.Property<long>("Unknown4Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("unknown4offset");

                    b.HasKey("Id")
                        .HasName("pk_subaction_header");

                    b.HasIndex("SubactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_subaction_header_subaction_id");

                    b.ToTable("subaction_header", (string)null);
                });

            modelBuilder.Entity("MoveSource", b =>
                {
                    b.Property<long>("MovesId")
                        .HasColumnType("bigint")
                        .HasColumnName("moves_id");

                    b.Property<long>("SourcesId")
                        .HasColumnType("bigint")
                        .HasColumnName("sources_id");

                    b.HasKey("MovesId", "SourcesId")
                        .HasName("pk_move_source");

                    b.HasIndex("SourcesId")
                        .HasDatabaseName("ix_move_source_sources_id");

                    b.ToTable("move_source", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.AutoCancelCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<bool>("AutoCancelEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_cancel_enabled");

                    b.ToTable("auto_cancel_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.BodyStateCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("BodyType")
                        .HasColumnType("integer")
                        .HasColumnName("body_type");

                    b.ToTable("body_state_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.HitboxCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Angle")
                        .HasColumnType("integer")
                        .HasColumnName("angle");

                    b.Property<int>("BaseKnockback")
                        .HasColumnType("integer")
                        .HasColumnName("base_knockback");

                    b.Property<int>("BoneId")
                        .HasColumnType("integer")
                        .HasColumnName("bone_id");

                    b.Property<int>("Damage")
                        .HasColumnType("integer")
                        .HasColumnName("damage");

                    b.Property<int>("Element")
                        .HasColumnType("integer")
                        .HasColumnName("element");

                    b.Property<int>("HitboxId")
                        .HasColumnType("integer")
                        .HasColumnName("hitbox_id");

                    b.Property<bool>("HitsAir")
                        .HasColumnType("boolean")
                        .HasColumnName("hits_air");

                    b.Property<bool>("HitsGround")
                        .HasColumnType("boolean")
                        .HasColumnName("hits_ground");

                    b.Property<int>("HurtboxInteraction")
                        .HasColumnType("integer")
                        .HasColumnName("hurtbox_interaction");

                    b.Property<int>("KnockbackGrowth")
                        .HasColumnType("integer")
                        .HasColumnName("knockback_growth");

                    b.Property<int>("SFX")
                        .HasColumnType("integer")
                        .HasColumnName("sfx");

                    b.Property<int>("ShieldDamage")
                        .HasColumnType("integer")
                        .HasColumnName("shield_damage");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<int>("Unknown0")
                        .HasColumnType("integer")
                        .HasColumnName("unknown0");

                    b.Property<int>("UnknownQ")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_q");

                    b.Property<int>("UnknownR")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_r");

                    b.Property<int>("UnknownV")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_v");

                    b.Property<int>("WeightDependantKnockback")
                        .HasColumnType("integer")
                        .HasColumnName("weight_dependant_knockback");

                    b.Property<int>("XOffset")
                        .HasColumnType("integer")
                        .HasColumnName("x_offset");

                    b.Property<int>("YOffset")
                        .HasColumnType("integer")
                        .HasColumnName("y_offset");

                    b.Property<int>("ZOffset")
                        .HasColumnType("integer")
                        .HasColumnName("z_offset");

                    b.ToTable("hitbox_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.PartialBodystateCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Bone")
                        .HasColumnType("integer")
                        .HasColumnName("bone");

                    b.ToTable("partial_bodystate_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.PointerCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<long>("Pointer")
                        .HasColumnType("bigint")
                        .HasColumnName("pointer");

                    b.ToTable("pointer_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.StartLoopCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasColumnName("iterations");

                    b.ToTable("start_loop_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.ThrowCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Angle")
                        .HasColumnType("integer")
                        .HasColumnName("angle");

                    b.Property<int>("BaseKnockback")
                        .HasColumnType("integer")
                        .HasColumnName("base_knockback");

                    b.Property<int>("Damage")
                        .HasColumnType("integer")
                        .HasColumnName("damage");

                    b.Property<int>("KnockbackGrowth")
                        .HasColumnType("integer")
                        .HasColumnName("knockback_growth");

                    b.Property<int>("ThrowElement")
                        .HasColumnType("integer")
                        .HasColumnName("throw_element");

                    b.Property<int>("ThrowType")
                        .HasColumnType("integer")
                        .HasColumnName("throw_type");

                    b.Property<int>("WeightDependantKnockback")
                        .HasColumnType("integer")
                        .HasColumnName("weight_dependant_knockback");

                    b.ToTable("throw_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.TimerCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Frames")
                        .HasColumnType("integer")
                        .HasColumnName("frames");

                    b.ToTable("timer_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.UnsolvedCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.ToTable("unsolved_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.VisibilityCommand", b =>
                {
                    b.HasBaseType("FightCore.Models.Subactions.Commands.ScriptCommand");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.ToTable("visibility_commands", (string)null);
                });

            modelBuilder.Entity("FightCore.Models.AlternativeAnimation", b =>
                {
                    b.HasOne("FightCore.Models.AnimationCredit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId")
                        .HasConstraintName("fk_alternative_animations_animation_credits_credit_id");

                    b.HasOne("FightCore.Models.Move", "Move")
                        .WithMany("AlternativeAnimations")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alternative_animations_moves_move_id");

                    b.Navigation("Credit");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("FightCore.Models.Character", b =>
                {
                    b.HasOne("FightCore.Models.CharacterMiscInfo", "CharacterInfo")
                        .WithMany()
                        .HasForeignKey("CharacterInfoId")
                        .HasConstraintName("fk_characters_characters_misc_infos_character_info_id");

                    b.HasOne("FightCore.Models.CharacterStatistics", "CharacterStatistics")
                        .WithMany()
                        .HasForeignKey("CharacterStatisticsId")
                        .HasConstraintName("fk_characters_character_statistics_character_statistics_id");

                    b.Navigation("CharacterInfo");

                    b.Navigation("CharacterStatistics");
                });

            modelBuilder.Entity("FightCore.Models.Hit", b =>
                {
                    b.HasOne("FightCore.Models.Move", null)
                        .WithMany("Hits")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hits_moves_move_id");
                });

            modelBuilder.Entity("FightCore.Models.Hitbox", b =>
                {
                    b.HasOne("FightCore.Models.Hit", "Hit")
                        .WithMany("Hitboxes")
                        .HasForeignKey("HitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hitboxes_hits_hit_id");

                    b.Navigation("Hit");
                });

            modelBuilder.Entity("FightCore.Models.Move", b =>
                {
                    b.HasOne("FightCore.Models.AnimationCredit", "AnimationCredit")
                        .WithMany()
                        .HasForeignKey("AnimationCreditId")
                        .HasConstraintName("fk_moves_animation_credits_animation_credit_id");

                    b.HasOne("FightCore.Models.Character", "Character")
                        .WithMany("Moves")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moves_characters_character_id");

                    b.Navigation("AnimationCredit");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.ScriptCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Subaction", null)
                        .WithMany("Commands")
                        .HasForeignKey("SubactionId")
                        .HasConstraintName("fk_script_commands_subactions_subaction_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.MoveSubaction", b =>
                {
                    b.HasOne("FightCore.Models.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_move_subactions_moves_move_id");

                    b.HasOne("FightCore.Models.Subactions.Subaction", "Subaction")
                        .WithMany("MoveSubactions")
                        .HasForeignKey("SubactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_move_subactions_subactions_subaction_id");

                    b.Navigation("Move");

                    b.Navigation("Subaction");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Subaction", b =>
                {
                    b.HasOne("FightCore.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subactions_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.SubactionHeader", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Subaction", "Subaction")
                        .WithOne("Header")
                        .HasForeignKey("FightCore.Models.Subactions.SubactionHeader", "SubactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subaction_header_subactions_subaction_id");

                    b.Navigation("Subaction");
                });

            modelBuilder.Entity("MoveSource", b =>
                {
                    b.HasOne("FightCore.Models.Move", null)
                        .WithMany()
                        .HasForeignKey("MovesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_move_source_moves_moves_id");

                    b.HasOne("FightCore.Models.Source", null)
                        .WithMany()
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_move_source_sources_sources_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.AutoCancelCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.AutoCancelCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_cancel_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.BodyStateCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.BodyStateCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_body_state_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.HitboxCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.HitboxCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hitbox_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.PartialBodystateCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.PartialBodystateCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partial_bodystate_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.PointerCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.PointerCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pointer_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.StartLoopCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.StartLoopCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_start_loop_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.ThrowCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.ThrowCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_throw_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.TimerCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.TimerCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timer_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.UnsolvedCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.UnsolvedCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unsolved_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Commands.VisibilityCommand", b =>
                {
                    b.HasOne("FightCore.Models.Subactions.Commands.ScriptCommand", null)
                        .WithOne()
                        .HasForeignKey("FightCore.Models.Subactions.Commands.VisibilityCommand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visibility_commands_script_commands_id");
                });

            modelBuilder.Entity("FightCore.Models.Character", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("FightCore.Models.Hit", b =>
                {
                    b.Navigation("Hitboxes");
                });

            modelBuilder.Entity("FightCore.Models.Move", b =>
                {
                    b.Navigation("AlternativeAnimations");

                    b.Navigation("Hits");
                });

            modelBuilder.Entity("FightCore.Models.Subactions.Subaction", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Header");

                    b.Navigation("MoveSubactions");
                });
#pragma warning restore 612, 618
        }
    }
}
